apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "crunchy-postgres.fullname" . }}-bcgw
  labels: {{ include "crunchy-postgres.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ template "crunchy-postgres.fullname" . }}-bcgw
  port:
    targetPort: postgres
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None