kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "crunchy-postgres.fullname" . }}-allow-bcgw
  labels: {{- include "crunchy-postgres.selectorLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      postgres-operator.crunchydata.com/cluster: {{ template "crunchy-postgres.fullname" . }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
  policyTypes:
    - Ingress