# PROD specific overrides
global:
  config:
    seed:
      enabled: true

backend:
  pdb:
    enabled: true
    # Trying to force replicaCount to 1 during deployment so we only run the seed data scripts once.
  replicaCount: 1

frontend:
  pdb:
    enabled: true # enable it in PRODUCTION for having pod disruption budget.

