FROM node:22-alpine

# Install packages, build and keep only prod packages
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Set NODE_ENV environment variable
ENV NODE_ENV development

# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci

# Bundle app source
COPY . ./

RUN npm run build

RUN set -x \
        && chmod -R 777 /app/

RUN apk add postgresql-client npm

# Expose port - mostly a convention, for readability
EXPOSE 4007

# Start up command
ENTRYPOINT ["sh","/app/local_start.sh"]
