import React from 'react';
import { FormFieldType } from '../../../components/input-controls/IFormField';
import { TableColumn, ColumnSize } from '../../../components/table/TableColumn';
import { FillEye, FillPinMapFill } from '../../../components/common/icon';
import '../Search.css';

const getSiteSearchResultsColumns = (
  hiddenColumns: Set<string> = new Set(),
) => {
  const columns: TableColumn[] = [
    {
      id: 1,
      displayName: 'Site ID',
      active: true,
      graphQLPropertyName: 'id',
      groupId: 1,
      disabled: true,
      isDefault: true,
      sortOrder: 1,
      isChecked: true,
      displayType: getLinkColumnType(
        hiddenColumns,
        'Site ID',
        'id',
        '',
        '/site/details/',
      ),
      stickyCol: true,
    },
    new TableColumn(
      6,
      'Site Address',
      true,
      'addrLine_1,addrLine_2,addrLine_3',
      2,
      true,
      true,
      1,
      true,
      getColumnType(
        'Site Address',
        'addrLine_1,addrLine_2,addrLine_3',
        '',
        FormFieldType.Text,
        'custom-input-text',
      ),
      'site/details/',
      false,
      '',
      ColumnSize.Triple,
    ),
    new TableColumn(
      7,
      'City',
      true,
      'city',
      2,
      false,
      true,
      1,
      true,
      getColumnType('City', 'city', ''),
    ),
    new TableColumn(
      2,
      'Site Remediation Status',
      true,
      'srStatus',
      1,
      false,
      true,
      1,
      false,
      getColumnType('Site Remediation Status', 'srStatus', ''),
    ),
    new TableColumn(
      3,
      'Site Risk code',
      true,
      'siteRiskCode',
      1,
      false,
      true,
      1,
      false,
      getColumnType('Site Risk code', 'siteRiskCode', ''),
    ),
    new TableColumn(
      4,
      'General Description',
      true,
      'generalDescription',
      1,
      false,
      true,
      1,
      true,
      getColumnType(
        'General Description',
        'generalDescription',
        '',
        FormFieldType.Label,
        'custom-search-input-text custom-search-input-ellipsis',
      ),
    ),
    new TableColumn(
      5,
      'Common Name',
      true,
      'commonName',
      2,
      false,
      true,
      1,
      false,
      getColumnType('Common Name', 'commonName', ''),
    ),
    new TableColumn(
      8,
      'Latitude',
      true,
      'latdeg',
      1,
      false,
      true,
      1,
      false,
      getColumnType('Latitude', 'latdeg', ''),
    ),
    new TableColumn(
      9,
      'Latitude(D,M,S)',
      true,
      'latDegrees,latMinutes,latSeconds',
      3,
      false,
      true,
      1,
      false,
      getColumnType('Latitude(D,M,S)', 'latDegrees,latMinutes,latSeconds', ''),
    ),
    new TableColumn(
      10,
      'Longitude',
      true,
      'longdeg',
      3,
      false,
      true,
      1,
      false,
      getColumnType('Longitude', 'longdeg', ''),
    ),
    new TableColumn(
      11,
      'Longitude(D,M,S)',
      true,
      'longDegrees,longMinutes,longSeconds',
      3,
      false,
      true,
      1,
      false,
      getColumnType(
        'Longitude(D,M,S)',
        'longDegrees,longMinutes,longSeconds',
        '',
      ),
    ),
    new TableColumn(
      12,
      'Lat/Long Reliability',
      true,
      'latlongReliabilityFlag',
      2,
      false,
      true,
      1,
      false,
      getColumnType('Lat/Long Reliability', 'latlongReliabilityFlag', ''),
    ),
    new TableColumn(
      13,
      'Created By',
      true,
      'whoCreated',
      4,
      false,
      true,
      1,
      false,
      getColumnType('Created By', 'whoCreated', ''),
    ),
    new TableColumn(
      14,
      'Date Created',
      true,
      'whenCreated',
      4,
      false,
      true,
      1,
      false,
      getColumnType('Date Created', 'whenCreated', '', FormFieldType.Date),
    ),
    new TableColumn(
      15,
      'Last Updated',
      true,
      'whenCreated',
      4,
      false,
      true,
      1,
      true,
      getColumnType('Last Updated', 'whenCreated', '', FormFieldType.Date),
    ),
    new TableColumn(
      16,
      'Consultant Submitted',
      true,
      'consultantSubmitted',
      3,
      false,
      true,
      1,
      false,
      getColumnType('Consultant Submitted', 'consultantSubmitted', ''),
    ),
    hiddenColumns.has('map')
      ? null
      : {
          id: 17,
          displayName: 'Map',
          active: true,
          graphQLPropertyName: 'id',
          groupId: 4,
          disabled: true,
          isDefault: true,
          sortOrder: 1,
          isChecked: true,
          displayType: getLinkColumnType(
            hiddenColumns,
            'Map',
            'id',
            '',
            '/map?site=',
            'View',
            <FillPinMapFill />,
          ),
          linkRedirectionURL: '/map?site=',
          dynamicColumn: true,
          stickyCol: true,
        },
    {
      id: 18,
      displayName: 'Details',
      active: true,
      graphQLPropertyName: 'id',
      groupId: 4,
      disabled: true,
      isDefault: true,
      sortOrder: 1,
      isChecked: true,
      displayType: getLinkColumnType(
        hiddenColumns,
        'Details',
        'id',
        '',
        '/site/details/',
        'View',
        <FillEye />,
      ),
      linkRedirectionURL: 'site/details/',
      dynamicColumn: true,
      stickyCol: true,
    },
  ].filter((column): column is TableColumn => column !== null);

  return columns;
};

const getColumnTypeWithSticky = (
  label: string,
  propertyName: string,
  value: string,
) => {
  return {
    type: FormFieldType.Label,
    label: label,
    graphQLPropertyName: propertyName,
    value: value,
    customLabelCss: 'custom-lbl-text',
    customInputTextCss: 'custom-input-text',
    tableMode: true,
    stickyCol: true,
  };
};

const getColumnType = (
  label: string,
  propertyName: string,
  value: string,
  type: FormFieldType = FormFieldType.Label,
  customInputText: string = 'custom-search-input-text',
  customLabel?: string,
) => {
  return {
    type: type,
    label: label,
    graphQLPropertyName: propertyName,
    value: value,
    customLabelCss: customLabel,
    customInputTextCss: customInputText,
    tableMode: true,
    stickyCol: false,
  };
};

const getLinkColumnType = (
  hiddenColumns: Set<string>,
  label: string,
  propertyName: string,
  value: string,
  href: string,
  customLabel?: string,
  customIcon?: React.ReactNode,
) => {
  return {
    type: FormFieldType.Link,
    label: label,
    graphQLPropertyName: propertyName,
    value: value,
    customLabelCss: 'link-for-table',
    customInputTextCss: 'link-for-table',
    tableMode: true,
    stickyCol: true,
    href: href,
    customLinkValue: customLabel ?? null,
    customIcon: customIcon ?? null,
    componentName: hiddenColumns.has('map') ? 'Map' : 'Search',
    componentPath: hiddenColumns.has('map') ? 'map' : 'search',
  };
};

export { getSiteSearchResultsColumns };

export const B: any = 1;
