{{- if .Values.frontendSiteRegistry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontendSiteRegistry.fullname" . }}
  labels:
    {{- include "frontendSiteRegistry.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.frontendSiteRegistry.deploymentStrategy }}
  {{- if not .Values.frontendSiteRegistry.autoscaling.enabled }}
  replicas: {{ .Values.frontendSiteRegistry.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frontendSiteRegistry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "frontendSiteRegistry.labels" . | nindent 8 }}
    spec:
      {{- if .Values.frontendSiteRegistry.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.frontendSiteRegistry.podSecurityContext | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ include "frontendSiteRegistry.fullname" . }}
          securityContext:
            capabilities:
              add: [ "NET_BIND_SERVICE" ]
          image: "{{.Values.global.registry}}/{{.Values.global.repository}}/frontend/site-registry:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "Always" .Values.frontendSiteRegistry.imagePullPolicy }}
          env:
            - name: REACT_APP_BACKEND_API
              value: "https://{{ .Release.Name }}-backendSites.{{ .Values.global.domain }}"
            - name: LOG_LEVEL
              value: "info"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          #-- the liveness probe for the container. it is optional and is an object. for default values check this link: https://github.com/bcgov/helm-service/blob/main/charts/component/templates/deployment.yaml#L324-L328
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 30m
              memory: 50Mi
          volumeMounts:
            - name: {{ .Release.Name }}-config
              mountPath: /usr/share/nginx/html/config/
      volumes:
        - name: {{ .Release.Name }}-config
          configMap:
            name: {{ include "frontendSiteRegistry.fullname" . }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "frontendSiteRegistry.fullname" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"

{{- end }}
