query mapSearch($searchParam: String) {
    mapSearch(searchParam: $searchParam) {
        data {
            id
            addrLine_1
            latdeg
            longdeg
        }
    }
}

query MapSearch_findSiteBySiteId($siteId: String!) {
    findSiteBySiteId(siteId: $siteId) {
        data {
            id
            addrLine_1
            addrLine_2
            addrLine_3
            addrLine_4
            city
            latdeg
            longdeg
            latDegrees
            latMinutes
            latSeconds
            longDegrees
            longMinutes
            longSeconds
            generalDescription
            siteRiskCode
        }
    }
}
