query mapSearch($searchParam: String) {
  mapSearch(searchParam: $searchParam) {
    data {
      id
      addrLine_1
      latdeg
      longdeg
    }
  }
}

query MapSearch_findSiteBySiteId($siteId: String!) {
  findSiteBySiteId(siteId: $siteId) {
    data {
      id
      addrLine_1
      addrLine_2
      addrLine_3
      addrLine_4
      city
      latdeg
      longdeg
      latDegrees
      latMinutes
      latSeconds
      longDegrees
      longMinutes
      longSeconds
      generalDescription
      siteRiskCode
    }
  }
}

query MapSearch_filterSearchResults(
  $page: Int!
  $pageSize: Int!
  $filters: SiteFilters!
) {
  searchSites(
    searchParam: ""
    page: $page
    pageSize: $pageSize
    filters: $filters
  ) {
    sites {
      id
      addrLine_1
      addrLine_2
      addrLine_3
      city
      srStatus
      siteRiskCode
      generalDescription
      commonName
      latdeg
      latDegrees
      latMinutes
      latSeconds
      longdeg
      longDegrees
      longMinutes
      longSeconds
      latlongReliabilityFlag
      whoCreated
      whenCreated
      whenCreated
      consultantSubmitted
    }
    count
    page
    pageSize
  }
}

mutation MapSearch_addCartItem($siteId: String!) {
  addCartItem(cartDTO: { siteId: $siteId, price: 0 }) {
    success
  }
}

query MapSearch_findSitesAndPlaces($searchParam: String!) {
  findSitesAndPlaces(searchParam: $searchParam) {
    sites {
      id
      commonName
      latdeg
      longdeg
    }
    places {
      id
      name
      latdeg
      longdeg
    }
  }
}
