import {
  FillEye,
  FillPinMapFill,
  TrashCanIcon,
} from '../../components/common/icon';
import { FormFieldType } from '../../components/input-controls/IFormField';
import { ColumnSize, TableColumn } from '../../components/table/TableColumn';

export const CartTableColumns: TableColumn[] = [
  {
    id: 1,
    displayName: 'Site ID',
    active: true,
    graphQLPropertyName: 'siteId',
    displayType: {
      type: FormFieldType.Link,
      label: 'Site ID',
      graphQLPropertyName: 'siteId',
      value: '',
      customInputTextCss: 'custom-cart-input-txt',
      tableMode: true,
      href: 'site/details/',
    },
    columnSize: ColumnSize.Small,
  },
  {
    id: 2,
    displayName: 'Site Address',
    active: true,
    graphQLPropertyName: 'addrLine_1,addrLine_2,addrLine_3',
    displayType: {
      type: FormFieldType.Text,
      label: 'Site Address',
      graphQLPropertyName: 'addrLine_1,addrLine_2,addrLine_3',
      value: '',
      customInputTextCss: 'custom-cart-input-txt',
      tableMode: true,
    },
    columnSize: ColumnSize.Double,
  },
  {
    id: 3,
    displayName: 'City',
    active: true,
    graphQLPropertyName: 'city',
    displayType: {
      type: FormFieldType.Text,
      label: 'City',
      graphQLPropertyName: 'city',
      value: '',
      customInputTextCss: 'custom-cart-input-txt',
      tableMode: true,
    },
    columnSize: ColumnSize.Double,
  },
  {
    id: 4,
    displayName: 'Price',
    active: true,
    graphQLPropertyName: 'price',
    dynamicColumn: true,
    displayType: {
      type: FormFieldType.Text,
      label: 'Price',
      graphQLPropertyName: 'price',
      value: '',
      customInputTextCss: 'custom-cart-input-txt',
      tableMode: true,
    },
    columnSize: ColumnSize.Small,
  },
  {
    id: 5,
    displayName: 'Map',
    active: true,
    graphQLPropertyName: 'siteId',
    dynamicColumn: true,
    displayType: {
      type: FormFieldType.Link,
      label: 'Map',
      graphQLPropertyName: 'id',
      value: '',
      customLinkValue: 'View',
      customInputTextCss: 'custom-cart-icon-link justify-content-center',
      tableMode: true,
      href: '/map?site=',
      customIcon: <FillPinMapFill />,
    },
    columnSize: ColumnSize.Small,
    customHeaderCss: 'text-center',
  },
  {
    id: 6,
    displayName: 'Details',
    active: true,
    graphQLPropertyName: 'siteId',
    dynamicColumn: true,
    displayType: {
      type: FormFieldType.Link,
      label: 'Details',
      graphQLPropertyName: 'id',
      value: '',
      customLinkValue: 'View',
      customInputTextCss: 'custom-cart-icon-link justify-content-center',
      tableMode: true,
      href: 'site/details/',
      customIcon: <FillEye />,
    },
    customHeaderCss: 'text-center',
  },
  {
    id: 7,
    displayName: '',
    active: true,
    graphQLPropertyName: 'id',
    dynamicColumn: true,
    displayType: {
      type: FormFieldType.IconButton,
      label: '',
      graphQLPropertyName: 'id',
      value: '',
      customLinkValue: '',
      customInputTextCss: 'custom-cart-input-txt text-danger',
      tableMode: true,
      customIcon: <TrashCanIcon />,
    },
    stickyCol: true,
    customHeaderCss: 'custom-cart-table-header',
  },
];
