import { id } from 'date-fns/locale';
import {
  FormFieldType,
  IFormField,
} from '../../../components/input-controls/IFormField';
import { TableColumn } from '../../../components/table/TableColumn';
import './SummaryForm.css';
import {
  bceRegionCodeDrpdown,
  siteRiskCodeDrpdown,
  siteStatusCodeDrpdown,
} from '../dropdowns/DropdownSlice';
import { useSelector } from 'react-redux';

export const GetSummaryConfig = () => {
  const siteRiskCode = useSelector(siteRiskCodeDrpdown);
  const bceRegionCode = useSelector(bceRegionCodeDrpdown);
  const siteStatusCode = useSelector(siteStatusCodeDrpdown);

  const formRows: { [key: string]: IFormField } = {
    id: {
      type: FormFieldType.Text,
      label: 'Site ID',
      placeholder: 'Please enter site ID...',
      graphQLPropertyName: 'id',
      value: '',
      isDisabled: true,
      validation: {
        pattern: /^[0-9,\s]*$/,
        customMessage: 'Site ID can only contain numbers and commas',
      },
      allowNumbersOnly: true,
      colSize: 'col-lg-12 col-md-12 col-sm-12',
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
    },
    latitude: {
      type: FormFieldType.Group,
      label: 'Latitude (D, M, S)',
      value: '',
      isChildLabel: true,
      customLabelCss: 'custom-summary-lbl-text',
      customEditLabelCss: 'custom-summary-lbl-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      colSize: 'col-lg-6 col-md-6 col-sm-12',
      children: [
        {
          type: FormFieldType.Text,
          label: 'Degree',
          placeholder: 'Please enter degree...',
          graphQLPropertyName: 'latDegrees',
          value: '',
          suffix: 'd ',
          validation: {
            pattern: /^[0-9.\s]*$/,
            customMessage:
              'Latitude Degrees can only contain numbers and decimal points',
          },
          allowNumbersOnly: true,
          customLabelCss: 'custom-summary-lbl-text',
          customInputTextCss: 'custom-summary-input-text',
          customEditInputTextCss: 'custom-summary-edit-input',
          customEditLabelCss: 'custom-summary-lbl-text',
        },
        {
          type: FormFieldType.Text,
          label: 'Minutes',
          placeholder: 'Please enter minutes...',
          graphQLPropertyName: 'latMinutes',
          value: '',
          suffix: 'm ',
          validation: {
            pattern: /^[0-9.\s]*$/,
            customMessage:
              'Latitude Minutes can only contain numbers and decimal points',
          },
          allowNumbersOnly: true,
          customLabelCss: 'custom-summary-lbl-text',
          customInputTextCss: 'custom-summary-input-text',
          customEditInputTextCss: 'custom-summary-edit-input',
          customEditLabelCss: 'custom-summary-lbl-text',
        },
        {
          type: FormFieldType.Text,
          label: 'Seconds',
          placeholder: 'Please enter seconds...',
          graphQLPropertyName: 'latSeconds',
          value: '',
          suffix: 's ',
          validation: {
            pattern: /^[0-9.\s]*$/,
            customMessage:
              'Latitude Seconds can only contain numbers and decimal points',
          },
          allowNumbersOnly: true,
          customLabelCss: 'custom-summary-lbl-text',
          customInputTextCss: 'custom-summary-input-text',
          customEditInputTextCss: 'custom-summary-edit-input',
          customEditLabelCss: 'custom-summary-lbl-text',
        },
      ],
    },
    longitude: {
      type: FormFieldType.Group,
      label: 'Longitude (D, M, S)',
      value: '',
      isChildLabel: true,
      customLabelCss: 'custom-summary-lbl-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-6 col-md-6 col-sm-12',
      children: [
        {
          type: FormFieldType.Text,
          label: 'Degree',
          placeholder: 'Please enter degree...',
          graphQLPropertyName: 'longDegrees',
          value: '',
          suffix: 'd ',
          validation: {
            pattern: /^[0-9.\s]*$/,
            customMessage:
              'Longitude Degrees can only contain numbers and decimal points',
          },
          allowNumbersOnly: true,
          customLabelCss: 'custom-summary-lbl-text',
          customInputTextCss: 'custom-summary-input-text',
          customEditInputTextCss: 'custom-summary-edit-input',
          customEditLabelCss: 'custom-summary-lbl-text',
        },
        {
          type: FormFieldType.Text,
          label: 'Minutes',
          placeholder: 'Please enter minutes...',
          graphQLPropertyName: 'longMinutes',
          suffix: 'm ',
          value: '',
          validation: {
            pattern: /^[0-9.\s]*$/,
            customMessage:
              'Longitude Minutes can only contain numbers and decimal points',
          },
          allowNumbersOnly: true,
          customLabelCss: 'custom-summary-lbl-text',
          customInputTextCss: 'custom-summary-input-text',
          customEditInputTextCss: 'custom-summary-edit-input',
          customEditLabelCss: 'custom-summary-lbl-text',
        },
        {
          type: FormFieldType.Text,
          label: 'Seconds',
          placeholder: 'Please enter seconds...',
          graphQLPropertyName: 'longSeconds',
          suffix: 's ',
          value: '',
          validation: {
            pattern: /^[0-9.\s]*$/,
            customMessage:
              'Longitude Seconds can only contain numbers and decimal points',
          },
          allowNumbersOnly: true,
          customLabelCss: 'custom-summary-lbl-text',
          customInputTextCss: 'custom-summary-input-text',
          customEditInputTextCss: 'custom-summary-edit-input',
          customEditLabelCss: 'custom-summary-lbl-text',
        },
      ],
    },
    siteAddress: {
      type: FormFieldType.Text,
      label: 'Site Address',
      placeholder: 'Please enter site address...',
      graphQLPropertyName: 'addrLine_1',
      value: '',
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-9 col-md-9 col-sm-12',
      validation: {
        required: true,
        customMessage: 'Site Address is required',
      },
    },
    addrType: {
      type: FormFieldType.DropDown,
      label: 'Address Type',
      placeholder: 'Please select address type...',
      graphQLPropertyName: 'addrType',
      // Keep this list in sync with the backend VALID_ADDR_TYPES constant.
      options: [
        { key: 'CIVIC', value: 'Civic' },
        { key: 'MAILING', value: 'Mailing' },
        { key: 'LEGAL', value: 'Legal' },
        { key: 'RA', value: 'RA' },
      ],
      value: '',
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-3 col-md-3 col-sm-12',
      validation: {
        required: true,
        customMessage: 'Address Type is required',
      },
    },
    provState: {
      type: FormFieldType.Text,
      label: 'Province',
      placeholder: 'Please enter Province abbreviation...',
      graphQLPropertyName: 'provState',
      isDisabled: true,
      value: 'BC',
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-3 col-md-3 col-sm-12',
    },
    city: {
      type: FormFieldType.Text,
      label: 'City',
      placeholder: 'Please enter city...',
      graphQLPropertyName: 'city',
      value: '',
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-3 col-md-3 col-sm-12',
      validation: {
        required: true,
        customMessage: 'City is required',
      },
    },
    postalCode: {
      type: FormFieldType.Text,
      label: 'Postal Code',
      placeholder: 'Please enter postal code...',
      graphQLPropertyName: 'postalCode',
      value: '',
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-3 col-md-3 col-sm-12',
    },
    bceRegionCode: {
      type: FormFieldType.DropDown,
      label: 'Region',
      placeholder: 'Please select a region...',
      graphQLPropertyName: 'bcerCode',
      value: '',
      options: bceRegionCode?.data || [],
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-3 col-md-3 col-sm-12',
      validation: {
        required: true,
        customMessage: 'Region is required',
      },
    },
    siteRiskCode: {
      type: FormFieldType.DropDown,
      label: 'Site Risk Classification',
      placeholder: 'Please select a site risk classification...',
      graphQLPropertyName: 'siteRiskCode',
      value: '',
      options: siteRiskCode?.data || [],
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-4 col-md-12 col-sm-12',
      validation: {
        required: true,
        customMessage: 'Site Risk Classification is required',
      },
    },
    siteStatusCode: {
      type: FormFieldType.DropDown,
      label: 'Site Status',
      placeholder: 'Please select a site status...',
      graphQLPropertyName: 'sstCode',
      value: '',
      options: siteStatusCode?.data || [],
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-4 col-md-12 col-sm-12',
      validation: {
        required: true,
        customMessage: 'Site Status is required',
      },
    },
    latlongReliabilityFlag: {
      type: FormFieldType.DropDown,
      label: 'Lat/Long Reliability',
      placeholder: 'Please select Lat/Long Reliability...',
      graphQLPropertyName: 'latlongReliabilityFlag',
      options: [
        { key: 'VERIFIED', value: 'VERIFIED' },
        { key: 'UNCONFIRMED', value: 'UNCONFIRMED' },
      ],
      value: '',
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-4 col-md-12 col-sm-12',
      validation: {
        required: true,
        customMessage: 'Lat/Long Reliability is required',
      },
    },
    commonName: {
      type: FormFieldType.Text,
      label: 'Common Name',
      placeholder: 'Please enter common name...',
      graphQLPropertyName: 'commonName',
      value: '',
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-12 col-md-12 col-sm-12',
      validation: {
        required: true,
        customMessage: 'Common Name is required',
      },
    },
  };

  const locationDescription = [
    {
      type: FormFieldType.Text,
      label: 'Location Description',
      placeholder: 'Location Description',
      graphQLPropertyName: 'generalDescription',
      value: '',
      customLabelCss: 'custom-summary-lbl-text',
      customInputTextCss: 'custom-summary-input-text',
      customEditInputTextCss: 'custom-summary-edit-input',
      customEditLabelCss: 'custom-summary-lbl-text',
      colSize: 'col-lg-12 col-md-12 col-sm-12',
    },
  ];

  const createSiteFormRows: IFormField[][] = [
    [formRows.latitude, formRows.longitude],
    [
      formRows.siteStatusCode,
      formRows.latlongReliabilityFlag,
      formRows.siteRiskCode,
    ],
    [formRows.addrType, formRows.siteAddress],
    [
      formRows.bceRegionCode,
      formRows.city,
      formRows.provState,
      formRows.postalCode,
    ],
    [formRows.commonName],
    locationDescription,
  ];

  const summaryFormRows: IFormField[][] = [
    [formRows.id],
    [formRows.latitude, formRows.longitude],
    [
      {
        ...formRows.siteAddress,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
      },
      {
        ...formRows.siteRiskCode,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
      },
    ],
    [formRows.commonName],
  ];

  const summaryColumns: TableColumn[] = [
    {
      id: 4,
      displayName: 'Notations',
      active: true,
      graphQLPropertyName: 'eventCount',
      displayType: {
        type: FormFieldType.Text,
        label: 'Site ID',
        placeholder: 'Separate IDs by a comma (",")',
        graphQLPropertyName: 'eventCount',
        value: '',
        validation: {
          pattern: /^[0-9,\s]*$/,
          customMessage: 'Site ID can only contain numbers and commas',
        },
        allowNumbersOnly: true,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
        customLabelCss: 'custom-lbl-text',
        customInputTextCss: 'custom-input-text',
        tableMode: true,
      },
      dynamicColumn: true,
    },
    {
      id: 5,
      displayName: 'Participants',
      active: true,
      graphQLPropertyName: 'eventParticCount',
      displayType: {
        type: FormFieldType.Text,
        label: 'Site ID',
        placeholder: 'Separate IDs by a comma (",")',
        graphQLPropertyName: 'eventParticCount',
        value: '',
        validation: {
          pattern: /^[0-9,\s]*$/,
          customMessage: 'Site ID can only contain numbers and commas',
        },
        allowNumbersOnly: true,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
        customLabelCss: 'custom-lbl-text',
        customInputTextCss: 'custom-input-text',
        tableMode: true,
      },
      dynamicColumn: true,
    },
    {
      id: 1,
      displayName: 'Documents',
      active: true,
      graphQLPropertyName: 'siteDocCount',
      displayType: {
        type: FormFieldType.Text,
        label: 'Site ID',
        placeholder: 'Separate IDs by a comma (",")',
        graphQLPropertyName: 'siteDocCount',
        value: '',
        validation: {
          pattern: /^[0-9,\s]*$/,
          customMessage: 'Site ID can only contain numbers and commas',
        },
        allowNumbersOnly: true,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
        customLabelCss: 'custom-lbl-text',
        customInputTextCss: 'custom-input-text',
        tableMode: true,
      },
      dynamicColumn: true,
    },
    {
      id: 2,
      displayName: 'Land Uses',
      active: true,
      graphQLPropertyName: 'landHistoryCount',
      displayType: {
        type: FormFieldType.Text,
        label: 'Site ID',
        placeholder: 'Separate IDs by a comma (",")',
        graphQLPropertyName: 'landHistoryCount',
        value: '',
        validation: {
          pattern: /^[0-9,\s]*$/,
          customMessage: 'Site ID can only contain numbers and commas',
        },
        allowNumbersOnly: true,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
        customLabelCss: 'custom-lbl-text',
        customInputTextCss: 'custom-input-text',
        tableMode: true,
      },
      dynamicColumn: true,
    },
    {
      id: 3,
      displayName: 'Associated Sites',
      active: true,
      graphQLPropertyName: 'siteAssocCount',
      displayType: {
        type: FormFieldType.Text,
        label: 'Site ID',
        placeholder: 'Separate IDs by a comma (",")',
        graphQLPropertyName: 'siteAssocCount',
        value: '',
        validation: {
          pattern: /^[0-9,\s]*$/,
          customMessage: 'Site ID can only contain numbers and commas',
        },
        allowNumbersOnly: true,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
        customLabelCss: 'custom-lbl-text',
        customInputTextCss: 'custom-input-text',
        tableMode: true,
      },
      dynamicColumn: true,
    },
    {
      id: 6,
      displayName: 'Parcel Description',
      active: true,
      graphQLPropertyName: 'siteSubdivCount',
      displayType: {
        type: FormFieldType.Text,
        label: 'Site ID',
        placeholder: 'Separate IDs by a comma (",")',
        graphQLPropertyName: 'siteSubdivCount',
        value: '',
        validation: {
          pattern: /^[0-9,\s]*$/,
          customMessage: 'Site ID can only contain numbers and commas',
        },
        allowNumbersOnly: true,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
        customLabelCss: 'custom-lbl-text',
        customInputTextCss: 'custom-input-text',
        tableMode: true,
      },
      dynamicColumn: true,
    },
  ];

  const summaryActivityColumns: TableColumn[] = [
    {
      id: 1,
      displayName: 'Activity',
      active: true,
      graphQLPropertyName: 'activity',
      displayType: {
        type: FormFieldType.Text,
        label: 'Site ID',
        placeholder: 'Separate IDs by a comma (",")',
        graphQLPropertyName: 'activity',
        value: '',

        allowNumbersOnly: true,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
        customLabelCss: 'custom-lbl-text',
        customInputTextCss: 'custom-input-text',
        tableMode: true,
      },
    },
    {
      id: 2,
      displayName: 'User',
      active: true,
      graphQLPropertyName: 'user',
      displayType: {
        type: FormFieldType.Text,
        label: 'Site ID',
        placeholder: 'Separate IDs by a comma (",")',
        graphQLPropertyName: 'user',
        value: '',
        validation: {
          pattern: /^[0-9,\s]*$/,
          customMessage: 'Site ID can only contain numbers and commas',
        },
        allowNumbersOnly: true,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
        customLabelCss: 'custom-lbl-text',
        customInputTextCss: 'custom-input-text',
        tableMode: true,
      },
    },
    {
      id: 3,
      displayName: 'Time Stamp',
      active: true,
      graphQLPropertyName: 'timeStamp',
      displayType: {
        type: FormFieldType.Text,
        label: 'Site ID',
        placeholder: 'Separate IDs by a comma (",")',
        graphQLPropertyName: 'timeStamp',
        value: '',
        validation: {
          pattern: /^[0-9,\s]*$/,
          customMessage: 'Site ID can only contain numbers and commas',
        },
        allowNumbersOnly: true,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
        customLabelCss: 'custom-lbl-text',
        customInputTextCss: 'custom-input-text',
        tableMode: true,
      },
    },
    {
      id: 4,
      displayName: 'SR',
      active: true,
      graphQLPropertyName: 'id',
      displayType: {
        type: FormFieldType.Text,
        label: 'Site ID',
        placeholder: 'Separate IDs by a comma (",")',
        graphQLPropertyName: 'id',
        value: '',
        validation: {
          pattern: /^[0-9,\s]*$/,
          customMessage: 'Site ID can only contain numbers and commas',
        },
        allowNumbersOnly: true,
        colSize: 'col-lg-6 col-md-6 col-sm-12',
        customLabelCss: 'custom-lbl-text',
        customInputTextCss: 'custom-input-text',
        tableMode: true,
      },
    },
  ];

  return {
    summaryFormRows,
    locationDescription,
    summaryColumns,
    summaryActivityColumns,
    createSiteFormRows,
  };
};
