---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Deployment template for a adjudication api service.
    tags: "${API_NAME}"
  name: "${API_NAME}-deploy"
objects:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: ${API_NAME}
    labels:
      app: "${API_NAME}"
      app-group: "${APP_GROUP}"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "${API_NAME}"
    template:
      metadata:
        labels:
          app: "${API_NAME}"
      spec:
        containers:
          - name: ${API_NAME}-container
            image: ${IMAGE_STREAM_NAME_FULL} 
            ports:
              - containerPort: 8080
            env:
              - name: POSTGRESQL_HOST
                value: nr-site-registry-postgresql
              - name: POSTGRESQL_PORT
                value: '5432'
              - name: POSTGRES_ADMIN_USERNAME
                valueFrom: 
                  secretKeyRef:
                    name: nr-site-registry-postgresql
                    key: database-user
              - name: POSTGRES_ADMIN_PASSWORD
                valueFrom: 
                  secretKeyRef:
                    name: nr-site-registry-postgresql
                    key: database-password
              - name: POSTGRES_DB_USERNAME
                valueFrom: 
                  secretKeyRef:
                    name: nr-site-registry-postgresql
                    key: database-user
              - name: POSTGRES_DB_PASSWORD
                valueFrom: 
                  secretKeyRef:
                    name: nr-site-registry-postgresql
                    key: database-password
              - name: POSTGRES_DATABASE
                valueFrom: 
                  secretKeyRef:
                    name: nr-site-registry-postgresql
                    key: database-name
              - name: POSTGRES_DB_SCHEMA
                value: sites
              - name: KEYCLOCK_AUTH_URL
                value: https://epd-keycloak-dev.apps.silver.devops.gov.bc.ca/auth
              - name: KEYCLOCK_CLIENT_ID
                value: site-service
              - name: KEYCLOCK_REALM
                value: forms-flow-ai
              - name: KEYCLOCK_SECRET
                value: 505142cf-9286-4e8f-b02f-f7b11023be1e
        initContainers:
            - name: site-registry-db-migration-applications
              image: "image-registry.openshift-image-registry.svc:5000/c6a6e5-tools/site-registry-backend-migrations:dev"
              env:
                - name: POSTGRESQL_HOST
                  value: nr-site-registry-postgresql
                - name: POSTGRESQL_PORT
                  value: '5432'
                - name: POSTGRES_ADMIN_USERNAME
                  valueFrom: 
                    secretKeyRef:
                      name: nr-site-registry-postgresql
                      key: database-user
                - name: POSTGRES_ADMIN_PASSWORD
                  valueFrom: 
                    secretKeyRef:
                      name: nr-site-registry-postgresql
                      key: database-password
                - name: POSTGRES_DB_USERNAME
                  valueFrom: 
                    secretKeyRef:
                      name: nr-site-registry-postgresql
                      key: database-user
                - name: POSTGRES_DB_PASSWORD
                  valueFrom: 
                    secretKeyRef:
                      name: nr-site-registry-postgresql
                      key: database-password
                - name: POSTGRES_DATABASE
                  valueFrom: 
                    secretKeyRef:
                      name: nr-site-registry-postgresql
                      key: database-name
                - name: POSTGRES_DB_SCHEMA
                  value: sites
                - name: KEYCLOCK_AUTH_URL
                  value: https://epd-keycloak-dev.apps.silver.devops.gov.bc.ca/auth
                - name: KEYCLOCK_CLIENT_ID
                  value: site-service
                - name: KEYCLOCK_REALM
                  value: forms-flow-ai
                - name: KEYCLOCK_SECRET
                  value: 505142cf-9286-4e8f-b02f-f7b11023be1e

- kind: Service
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
    creationTimestamp: 
    labels:
      app: "${API_NAME}"
      app-group: "${APP_GROUP}"
      template: "${API_NAME}-deploy"
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      app: "${API_NAME}"
    type: ClusterIP
    sessionAffinity: None
  # status:
  #   loadBalancer: {}
- kind: Route
  apiVersion: v1
  metadata:
    name: "${API_NAME}"
    labels:
      app: "${API_NAME}"
      app-group: "${APP_GROUP}"
      template: "${API_NAME}-deploy"
  spec:
    to:
      kind: Service
      name: "${API_NAME}"
      weight: 100
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    wildcardPolicy: None
    host: "${API_NAME}-${TAG_NAME}.apps.silver.devops.gov.bc.ca"
parameters:
- name: API_NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
  value: site-registry-backend
- name: APP_GROUP
  displayName: App Group
  description: The name assigned to all of the deployments in this project.
  required: true
  value: site-registry
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: IMAGE_STREAM_NAME_FULL
  displayName: Full image stream name (eg "frontend:dev")
  description: Includes ImageStream name and tag
  required: true
  value: image-registry.openshift-image-registry.svc:5000/c6a6e5-tools/site-registry-backend:dev