import { FormFieldType } from '../../../components/input-controls/IFormField';
import { TableColumn } from '../../../components/table/TableColumn';

export const columns: TableColumn[] = [
  {
    id: 1,
    displayName: 'Description Type',
    active: true,
    graphQLPropertyName: 'descriptionType',
    groupId: 1,
    disabled: true,
    isDefault: true,
    sortOrder: 1,
    isChecked: true,
    displayType: {
      type: FormFieldType.Label,
      label: 'DescriptionType',
      graphQLPropertyName: 'descriptionType',
      value: '',
      customLabelCss: 'custom-lbl-text',
      customInputTextCss: 'custom-input-text',
      tableMode: true,
      stickyCol: false,
    },
    stickyCol: true,
  },
  {
    id: 2,
    displayName: 'ID/PIN/Number',
    active: true,
    graphQLPropertyName: 'idPinNumber',
    groupId: 1,
    disabled: true,
    isDefault: true,
    sortOrder: 1,
    isChecked: true,
    displayType: {
      type: FormFieldType.Label,
      label: 'ID/PIN/Number',
      graphQLPropertyName: 'idPinNumber',
      value: '',
      customLabelCss: 'custom-lbl-text',
      customInputTextCss: 'custom-input-text',
      tableMode: true,
      stickyCol: false,
    },
    stickyCol: true,
  },
  {
    id: 3,
    displayName: 'Date Noted',
    active: true,
    graphQLPropertyName: 'dateNoted',
    groupId: 1,
    disabled: true,
    isDefault: true,
    sortOrder: 1,
    isChecked: true,
    displayType: {
      type: FormFieldType.Label,
      label: 'Date Noted',
      graphQLPropertyName: 'dateNoted',
      value: '',
      customLabelCss: 'custom-lbl-text',
      customInputTextCss: 'custom-input-text',
      tableMode: true,
      stickyCol: false,
    },
    stickyCol: true,
  },
  {
    id: 4,
    displayName: 'Land Description',
    active: true,
    graphQLPropertyName: 'landDescription',
    groupId: 1,
    disabled: true,
    isDefault: true,
    sortOrder: 1,
    isChecked: true,
    displayType: {
      type: FormFieldType.Label,
      label: 'Land Description',
      graphQLPropertyName: 'landDescription',
      value: '',
      customLabelCss: 'custom-lbl-text',
      customInputTextCss: 'custom-input-text',
      tableMode: true,
      stickyCol: false,
    },
    stickyCol: true,
  },
];
