# Only ovverride values-test.yaml if the environment is TEST with the following values as a delta:
crunchy: # enable it for TEST and PROD, for PR based pipelines simply use single postgres
  instances:
    dataVolumeClaimSpec:
      storage: 200Mi
      storageClassName: netapp-block-standard
      walStorage: 220Mi
  clone:
    enabled: true # enable it when the dev cluster needs to be cloned from test
    s3:
      enabled: true
    pvc:
      enabled: false
    path: /backups/test/cluster/version/2
  pgBackRest:
    clusterCounter: 4 # for some reason 1, did not work, putting it to 2 worked, so updating it in pipelines.
    backupPath: /backups/test/cluster/version # change it for PROD, create values-prod.yaml
    s3:
      enabled: true
      retention: 1 # one weeks backup in object store for test environment
      bucket: nrsitetst
      endpoint: nrs.objectstore.gov.bc.ca
      accessKey: ~
      secretKey: ~
      fullBackupSchedule: 0 9 * * * # full backup at GMT 9
      incrementalBackupSchedule: 0 0/4 * * * # every fifteen minutes except 0th
    pvc:
      enabled: false