crunchy:
  instances:
    dataVolumeClaimSpec:
      # TODO, want to increase to 1Gi, but low on space now, that was the issue.
      storage: 250Mi
      storageClassName: netapp-block-standard
      walStorage: 100Mi
  clone:
    enabled: false 
    s3:
      enabled: false
    pvc:
      enabled: false
    path: ~ 
  pgBackRest:
    # clusterCounter: 4 # for some reason 1, did not work, putting it to 2 worked, so updating it in pipelines.
    backupPath: /backups/prod/cluster/version # change it for PROD, create values-prod.yaml
    s3:
      enabled: true
      retention: 1 # one day backup in object store for test environment
      bucket: nrsiteprod
      endpoint: nrs.objectstore.gov.bc.ca
      accessKey: ~
      secretKey: ~
      fullBackupSchedule: 0 9 * * * # full backup at GMT 9
      incrementalBackupSchedule: 0 0/4 * * * # every four hours
    pvc:
      enabled: false