crunchy:
  instances:
    name: db
    replicas: 2
    dataVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 600Mi
      storageClassName: netapp-block-standard
    walVolumeClaimSpec:  # Move WAL config here
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 350Mi
      storageClassName: netapp-block-standard
  pgBackRest:
    backupPath: /backups/prod/cluster/version
    s3:
      enabled: true
      retention: 7
      bucket: nrsiteprd
      endpoint: nrs.objectstore.gov.bc.ca
      fullBackupSchedule: 0 0/4 * * *
      incrementalBackupSchedule: 0 1,6,11,17,23 * * *
    pvc:
      enabled: false
  pgmonitor:
    enabled: true