crunchy:
  instances:
    dataVolumeClaimSpec:
      storage: 600Mi
      storageClassName: netapp-block-standard
      walStorage: 350Mi
    replicas: 2  # Explicitly ensure two instances, each with PVCs
  pgBackRest:
    backupPath: /backups/prod/cluster/version
    s3:
      enabled: true
      retention: 7  # One week backup in object store for prod environment
      bucket: nrsiteprd
      endpoint: nrs.objectstore.gov.bc.ca
      fullBackupSchedule: 0 0/4 * * *  # Full backup every 4 hours
      incrementalBackupSchedule: 0 1,6,11,17,23 * * *  # Incremental every 5 hours
    pvc:
      enabled: false  # Explicitly disable repo host PVC to match test
      volume:
        storage: 1024Mi  # Kept for reference, but ignored since enabled: false
  pgmonitor:
    enabled: true