kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: site-postgres-cluster-db-init
  namespace: c6a6e5-prod
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
