apiVersion: v1
kind: Secret
metadata:
  name: site-backend
  namespace: c6a6e5-prod
data:
  KEYCLOAK_SECRET: ''
  KEYCLOAK_REALM: ''
  KEYCLOAK_CLIENT_ID: ''
  KEYCLOAK_AUTH_URL: ''
  ESRA_S3_ENDPOINT: ''
  ESRA_S3_ACCESS_KEY: ''
  ESRA_S3_SECRET_KEY: ''
  ESRA_S3_BUCKET: ''
  ESRA_S3_BUCKET_ENV: ''
  CSV_SECRET: ''
  VITE_S3_STORAGE_SECRET_ACCESS_KEY: ''
  VITE_S3_STORAGE_BUCKET: ''
  VITE_S3_STORAGE_ACCESS_KEY_ID: ''
  VITE_S3_STORAGE_ENDPOINT: ''
  VITE_COMS_API: ''
  VITE_S3_STORAGE_REGION: ''
  VITE_COMS_BUCKET: ''
