apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nr-ora2pg-sql
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
    # Prod needs like 900Mi or more, test just 200Mi.
      storage: 700Mi
