#Keycloak
{{- $keycloackSecret:= .Values.global.secrets.keycloakSecret }}
{{- $keycloackRealm:= .Values.global.secrets.keycloakRealm }}
{{- $keycloackClientID:= .Values.global.secrets.keycloakClientID }}
{{- $keycloackAuthURL:= .Values.global.secrets.keycloakAuthURL }}

#ESRA S3
{{- $esraS3Endpoint := .Values.global.secrets.esraS3Endpoint }}
{{- $esraS3AccessKey := .Values.global.secrets.esraS3AccessKey }}
{{- $esraS3SecretKey := .Values.global.secrets.esraS3SecretKey }}
{{- $esraS3Bucket := .Values.global.secrets.esraS3Bucket }}
{{- $esraS3BucketEnv := .Values.global.secrets.esraS3BucketEnv }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend # secrets that will be only exposed to backend  container
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  KEYCLOCK_SECRET: {{ $keycloackSecret | b64enc | quote }}
  KEYCLOCK_REALM: {{ $keycloackRealm | b64enc | quote }}
  KEYCLOCK_CLIENT_ID: {{ $keycloackClientID | b64enc | quote }}
  KEYCLOCK_AUTH_URL: {{ $keycloackAuthURL | b64enc | quote }}
  ESRA_S3_ENDPOINT: {{ $esraS3Endpoint | b64enc | quote }}
  ESRA_S3_ACCESS_KEY: {{ $esraS3AccessKey | b64enc | quote }}
  ESRA_S3_SECRET_KEY: {{ $esraS3SecretKey | b64enc | quote }}
  ESRA_S3_BUCKET: {{ $esraS3Bucket | b64enc | quote }}
  ESRA_S3_BUCKET_ENV: {{ $esraS3BucketEnv | b64enc | quote }}
