{{- if and .Values.global.secrets .Values.global.secrets.enabled}}

#Keycloak
{{- $keycloackSecret:= .Values.global.secrets.keycloakSecret }}
{{- $keycloackRealm:= .Values.global.secrets.keycloakRealm }}
{{- $keycloackClientID:= .Values.global.secrets.keycloakClientID }}
{{- $keycloackAuthURL:= .Values.global.secrets.keycloakAuthURL }}

#database
{{- $databaseUser := .Values.global.secrets.databaseUser| default "site"  }} # look at auth section in values.yaml of bitnamipg if it is used.
{{- $databaseAdminUser := "postgres" }}
{{- $databasePassword := .Values.global.secrets.databasePassword | default (randAlphaNum 24) }}
{{- $databaseAdminPassword := .Values.global.secrets.databaseAdminPassword | default (randAlphaNum 24) }}
{{- $secretName := printf "%s-database" .Release.Name }}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName ) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
  # set below to existing secret data or generate a random one when not exists
{{- $databaseAdminPassword = (get $secretData "postgres-password") | default ($databasePassword | b64enc) }}
{{- $databasePassword = (get $secretData "password") | default ($databasePassword | b64enc) }}
{{- $databaseName := .Values.global.secrets.databaseName| default "site" }} # look at auth section in values.yaml of bitnamipg if it is used.
{{- $host := printf "%s-%s:5432" .Release.Name .Values.global.databaseAlias }}
{{- $port := printf "5432" }}
{{- $hostWithoutPort := printf "%s-%s" .Release.Name .Values.global.databaseAlias }}
{{- $databaseURL := printf "postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURL := printf "jdbc:postgresql://%s:%s@%s/%s" $databaseUser (b64dec $databasePassword) $host $databaseName }}
{{- $databaseJDBCURLNoCreds := printf "jdbc:postgresql://%s/%s" $host $databaseName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-sites # secrets that will be only exposed to backend-sites  container
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  POSTGRES_DB_PASSWORD: {{ $databasePassword | quote }}
  POSTGRES_DB_USERNAME: {{ $databaseUser | b64enc | quote }}
  POSTGRES_DATABASE: {{ $databaseName | b64enc | quote }}
  POSTGRESQL_HOST: {{ $hostWithoutPort | b64enc | quote }}
  POSTGRESQL_PORT: {{ $port | b64enc | quote }}
  POSTGRES_ADMIN_USERNAME: {{ $databaseAdminUser | b64enc | quote }}
  POSTGRES_ADMIN_PASSWORD: {{ $databaseAdminPassword | quote }}
  KEYCLOCK_SECRET: {{ $keycloackSecret | b64enc | quote }}
  KEYCLOCK_REALM: {{ $keycloackRealm | b64enc | quote }}
  KEYCLOCK_CLIENT_ID: {{ $keycloackClientID | b64enc | quote }}
  KEYCLOCK_AUTH_URL: {{ $keycloackAuthURL | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-sites-migrations # secrets that will be only exposed to backend sites migrations container.
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  POSTGRES_DB_PASSWORD: {{ $databasePassword | quote }}
  POSTGRES_DB_USERNAME: {{ $databaseUser | b64enc | quote }}
  POSTGRES_DATABASE: {{ $databaseName | b64enc | quote }}
  POSTGRESQL_HOST: {{ $hostWithoutPort | b64enc | quote }}
  POSTGRESQL_PORT: {{ $port | b64enc | quote }}
  POSTGRES_ADMIN_USERNAME: {{ $databaseAdminUser | b64enc | quote }}
  POSTGRES_ADMIN_PASSWORD: {{ $databaseAdminPassword | quote }}

---
apiVersion: v1
kind: Secret # secrets exposed to DB container only.
metadata:
  name: {{ .Release.Name }}-database
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  postgres-password: {{ $databasePassword  | quote }}
  password: {{ $databaseAdminPassword | quote }}
{{- end }}
