#Keycloak
{{- $keycloakSecret:= .Values.global.secrets.keycloakSecret }}
{{- $keycloakRealm:= .Values.global.secrets.keycloakRealm }}
{{- $keycloakClientID:= .Values.global.secrets.keycloakClientID }}
{{- $keycloakAuthURL:= .Values.global.secrets.keycloakAuthURL }}

#ESRA S3
{{- $esraS3Endpoint := .Values.global.secrets.esraS3Endpoint }}
{{- $esraS3AccessKey := .Values.global.secrets.esraS3AccessKey }}
{{- $esraS3SecretKey := .Values.global.secrets.esraS3SecretKey }}
{{- $esraS3Bucket := .Values.global.secrets.esraS3Bucket }}
{{- $esraS3BucketEnv := .Values.global.secrets.esraS3BucketEnv }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend # secrets that will be only exposed to backend  container
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  KEYCLOAK_SECRET: {{ $keycloakSecret | b64enc | quote }}
  KEYCLOAK_REALM: {{ $keycloakRealm | b64enc | quote }}
  KEYCLOAK_CLIENT_ID: {{ $keycloakClientID | b64enc | quote }}
  KEYCLOAK_AUTH_URL: {{ $keycloakAuthURL | b64enc | quote }}
  ESRA_S3_ENDPOINT: {{ $esraS3Endpoint | b64enc | quote }}
  ESRA_S3_ACCESS_KEY: {{ $esraS3AccessKey | b64enc | quote }}
  ESRA_S3_SECRET_KEY: {{ $esraS3SecretKey | b64enc | quote }}
  ESRA_S3_BUCKET: {{ $esraS3Bucket | b64enc | quote }}
  ESRA_S3_BUCKET_ENV: {{ $esraS3BucketEnv | b64enc | quote }}
