kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: site-backend
  namespace: c6a6e5-tools
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/nr-site-registry.git'
      ref: 'dev'
    contextDir: backend
  strategy:
    type: Docker
    dockerStrategy:
      env:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'site-backend:dev'
  triggers:
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: site-backend-init:dev
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
