#SITE/SIS properties for LTSA

# sis database
SIS_DATABASE=#{sis_database_name}
# TEST=envtest1.env.gov.bc.ca  
# PROD=envprod1.env.gov.bc.ca

SIS_PASSWORD=#{site_database_password}

account_pwd="sis/${SIS_PASSWORD}@${SIS_DATABASE}"

# lto sftp credentials
lto_username=siteregistry
lto_sftp_site=#{lto_sftp_site}
# TEST=sftptest.ltsa  
# PROD=sftp.ltsa.ca

# environment pathes
app_path=/apps_ux/sis
admin_path=${app_path}/admin
admin_lto_path=${admin_path}/lto
import_path=${app_path}/lto_task/import
export_path=${app_path}/lto_task/export

API_URL=#{api_url}
KEYCLOAK_URL=#{keycloak_url}
KEYCLOAK_REALM=#{keycloak_realm}
KEYCLOAK_CLIENT_ID=#{keycloak_client_id}
KEYCLOAK_CLIENT_SECRET=#{keycloak_client_secret}
