{{- if .Values.backend.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "backend.fullname" . }}-daily
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  schedule: "0 0 * * *"  # Run at midnight every day
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - curl -f http://{{ include "backend.fullname" . }}:{{ .Values.backend.service.port }}/csv/generate
          restartPolicy: OnFailure
{{- end }}