import { FillEye, FillPinMapFill } from '../../components/common/icon';
import { FormFieldType } from '../../components/input-controls/IFormField';
import { ColumnSize, TableColumn } from '../../components/table/TableColumn';

export const recentViewedColumns: TableColumn[] = [
  {
    id: 1,
    displayName: 'Site ID',
    active: true,
    graphQLPropertyName: 'siteId',
    displayType: {
      type: FormFieldType.Link,
      label: 'Site ID',
      graphQLPropertyName: 'siteId',
      value: '',
      customInputTextCss: 'custom-dashboard-input-txt',
      tableMode: true,
      href: 'site/details/',
    },
    linkRedirectionURL: 'site/details/',
    dynamicColumn: true,
  },
  {
    id: 2,
    displayName: 'Site Address',
    active: true,
    graphQLPropertyName: 'address',
    displayType: {
      type: FormFieldType.Label,
      label: 'Site Address',
      graphQLPropertyName: 'address',
      value: '',
      customInputTextCss: 'custom-dashboard-input-txt',
      tableMode: true,
    },
    dynamicColumn: true,
  },
  {
    id: 3,
    displayName: 'City',
    active: true,
    graphQLPropertyName: 'city',
    displayType: {
      type: FormFieldType.Label,
      label: 'City',
      graphQLPropertyName: 'city',
      value: '',
      customInputTextCss: 'custom-dashboard-input-txt',
      tableMode: true,
    },
    dynamicColumn: true,
  },
  {
    id: 4,
    displayName: 'General Description',
    active: true,
    graphQLPropertyName: 'generalDescription',
    displayType: {
      type: FormFieldType.Label,
      label: 'General Description',
      graphQLPropertyName: 'generalDescription',
      value: '',
      customInputTextCss: 'custom-dashboard-input-txt',
      tableMode: true,
    },
    columnSize: ColumnSize.Triple,
    dynamicColumn: true,
  },
  {
    id: 5,
    displayName: 'Last Updates',
    active: true,
    graphQLPropertyName: 'whenUpdated',
    displayType: {
      type: FormFieldType.Date,
      graphQLPropertyName: 'whenUpdated',
      label: '',
      placeholder: 'MM/DD/YY',
      value: '',
      colSize: 'col-lg-6 col-md-6 col-sm-12',
      customInputTextCss: 'custom-dashboard-input-txt',
      tableMode: true,
    },
    dynamicColumn: true,
  },
  {
    id: 6,
    displayName: 'Map',
    active: true,
    graphQLPropertyName: 'siteId',
    displayType: {
      type: FormFieldType.Link,
      label: 'Map',
      graphQLPropertyName: 'siteId',
      value: '',
      customLinkValue: 'View',
      customInputTextCss: 'custom-dashboard-link',
      tableMode: true,
      href: '/map?site=',
      customIcon: <FillPinMapFill />,
    },
    dynamicColumn: true,
  },
  {
    id: 7,
    displayName: 'Details',
    active: true,
    graphQLPropertyName: 'siteId',
    displayType: {
      type: FormFieldType.Link,
      label: 'Details',
      graphQLPropertyName: 'siteId',
      value: '',
      customLinkValue: 'View',
      customInputTextCss: 'custom-dashboard-link',
      tableMode: true,
      href: 'site/details/',
      customIcon: <FillEye />,
    },
    linkRedirectionURL: 'site/details/',
    dynamicColumn: true,
  },
];

export const actionsItemsConfig = [
  {
    label: 'Create a Site',
    value: 'create-site',
  },
  {
    label: 'Search for a Site',
    value: 'search-site',
  },
  {
    label: 'View Sites on Map',
    value: 'view-sites-on-map',
  },
];
