name: Deploy to PROD

# Merges into the dev branch will deploy to prod. 
# Currently this also deploys to test, so test and prod should be in sync.
on:
  push:
    branches:
      - dev
      - feat/ocp-prod # remove this after, just triggering build
      - dev-to-prod # another temp deploy branch, after squashing to new branch due to messy history.
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to deploy (optional)'
        required: false
        default: ''      
concurrency:
  # Cancel in progress for PR open and close
  group: prod
  cancel-in-progress: false

jobs:


  get-pr-info:
    if: github.ref_name == 'dev' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04
    outputs:
      pr: ${{ steps.set-pr.outputs.pr }}
    steps:
      - id: set-pr
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.pr }}" != "" ]; then
            echo "pr=${{ github.event.inputs.pr }}" >> $GITHUB_OUTPUT
          else
            echo "Fetching PR number from action-get-pr"
            pr_num=$(gh pr view --json number -q .number || echo "")
            echo "pr=$pr_num" >> $GITHUB_OUTPUT
          fi
      - name: Echo PR number
        run: |
          echo "PR: ${{ steps.set-pr.outputs.pr }}"

  # get-pr-info:
  #   if: github.ref_name == 'dev'  
  #   runs-on: ubuntu-24.04
  #   outputs:
  #     pr: ${{ steps.vars.outputs.pr }}
  #   steps:
  #     - id: vars
  #       uses: bcgov-nr/action-get-pr@v0.0.1
  #     - name: Echo PR number
  #       run: |
  #         echo "PR: ${{ steps.vars.outputs.pr }}"

# Typically, we do not build and deploy in the prod branch, we just re-use tags from other branches.
# But during development, it's nice to be able to build changes, eg migration changes as we work through prod data import.
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, frontend, backend-migration]
        include:
          - package: backend
            build_file: ./backend/Dockerfile
            build_context: backend
          - package: backend-migration
            build_file: ./backend/Dockerfile.migrations
            build_context: backend
          - package: frontend
            build_file: ./frontend/Dockerfile
            build_context: frontend
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          package: ${{ matrix.package }}
          # Use input tag if provided, otherwise fallback to branch name (feat-ocp-prod -> feat-ocp-prod)
          # tag: ${{ github.event.inputs.tag != '' && github.event.inputs.tag || github.ref_name }}
          # tag: prod
          tag: ${{ github.event.inputs.tag != '' && github.event.inputs.tag || 'prod' }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')
          build_file: ${{ matrix.build_file }}
          build_context: ${{ matrix.build_context }}
  ## Prod Deploy
  ## Curently trigering on merge to dev, we can change if desired
  ## So now, test and prod are identical from a code/commit perspective (differ in envs, db params, etc)

  deploy_db_prod:
    name: Deploys Database
    uses: ./.github/workflows/.dbdeployer.yml
    secrets: inherit
    with:
      environment: prod
      values: 'values-prod.yaml'
      app_values: 'values.yaml' # PROD env specific values file for the APP

      # Problem - if we need latest migration, we also need to change tag stuff.
      # this is using an old build, it's just deploying it.
  deploys_prod:
    name: Deploys to PROD
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    needs: [deploy_db_prod, builds]
    with:
      environment: prod
      values: 'values-prod.yaml' # PROD env specific values file, will override values.yaml key/values but default to values.yaml
      # tag: prod
      tag: ${{ github.event.inputs.tag != '' && github.event.inputs.tag || 'prod' }}
      # tag:  '${{ needs.get-pr-info.outputs.pr }}'




  # schemaspy:
  #   name: Schemaspy
  #   uses: ./.github/workflows/.schema-spy.yml
  #   secrets: inherit
  #   needs: [deploys]
  #   with:
  #     tag: prod
