name: Dev Merge - Deploy to TEST

on:
  push:
    branches:
      - dev

concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  get-pr-info:
    runs-on: ubuntu-24.04
    outputs:
      pr: ${{ steps.vars.outputs.pr }}
    steps:
      - id: vars
        uses: bcgov-nr/action-get-pr@v0.0.1
      - name: Echo PR number
        run: echo "PR: ${{ steps.vars.outputs.pr }}"
  
  deploys:
    name: Deploys to TEST
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    needs: [get-pr-info ]
    with:
      triggers: ('backend/' 'frontend/')
      environment: test
      tag:  ${{ needs.get-pr-info.outputs.pr }}
  
  schemaspy:
    name: Schemaspy
    uses: .github/workflows/.schema-spy.yml
    secrets: inherit
    needs: [deploys]
    with: 
      tag: test





