name: PR

on:
  pull_request:
    branches:
      - dev # this is the default branch and not main


concurrency:
  # Cancel in progress for PR open and close
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  # https://github.com/bcgov-nr/action-builder-ghcr
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: [backend, frontend, backend-migration]
        include:
          - package: backend
            build_file: ./backend/Dockerfile
            build_context: backend
          - package: backend-migration
            build_file: ./backend/Dockerfile.migrations
            build_context: backend
          - package: frontend
            build_file: ./frontend/Dockerfile
            build_context: frontend
    timeout-minutes: 10
    steps:
      - uses: bcgov-nr/action-builder-ghcr@v2.2.0
        with:
          package: ${{ matrix.package }}
          tag: ${{ github.event.number }}
          tag_fallback: latest
          triggers: ('${{ matrix.package }}/')
          build_file: ${{ matrix.build_file }}
          build_context: ${{ matrix.build_context }}

  # https://github.com/bcgov/quickstart-openshift-helpers
  deploys:
    name: Deploys
    if: ${{ ! github.event.pull_request.draft }}
    needs: [builds]
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      triggers: ('backend/' 'frontend/' 'charts/' '.github/workflows/')
      values: 'values-pr.yaml' # PR specific values file.

  results:
    name: PR Results
    needs: [builds, deploys]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - if: contains(needs.*.result, 'failure')
        run: echo "At least one job has failed." && exit 1
      - run: echo "Success!"
